steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west3-docker.pkg.dev/$PROJECT_ID/medibook-dev-repo/medibook-dev:$COMMIT_SHA', '.']
# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west3-docker.pkg.dev/$PROJECT_ID/medibook-dev-repo/medibook-dev:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: "gcr.io/cloud-builders/gcloud"
  args:
    - 'beta'
    - 'run'
    - 'deploy'
    - 'medibook-service'
    - '--image'
    - 'europe-west3-docker.pkg.dev/$PROJECT_ID/medicbook-dev-repo/medicbook-dev:$COMMIT_SHA'
    - '--region'
    - 'eu-west3'
    - '--allow-unauthenticated'
    - '--platform'
    - 'managed'
#
images:
- 'europe-west3-docker.pkg.dev/$PROJECT_ID/medibook-dev-repo/medibook-dev'