#
#substitutions:
#    _IMAGE_NAME: medicbook-dev
#    _GIT_REPO: https://github.com/xdanadav/medicbook.git
    
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west3-docker.pkg.dev/$PROJECT_ID/medibook-dev-repo/medicbook-dev:$COMMIT_SHA', '.']
# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west3-docker.pkg.dev/$PROJECT_ID/medicbook-dev-repo/medicbook-dev:$COMMIT_SHA']
# Deploy container image to Cloud Run
#- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#  entrypoint: gcloud
#  args:
#    - 'beta'
#    - 'run'
#    - 'deploy'
#    - 'svc-helloworld'
#    - '--image'
#    - 'eu-west3-docker.pkg.dev/$PROJECT_ID/medicbook-dev-repo/medicbook-dev:$COMMIT_SHA'
#    - '--region'
#    - 'eu-west3'
#    - '--platform'
#    - 'managed'
#    - '--min-instances'
#    - '0'
#    - '--max-instances'
#    - '1'
#    - '--allow-unauthenticated'

images:
- 'europe-west3-docker.pkg.dev/$PROJECT_ID/docker-images-repo/trigger-helloworld'
