substitutions:
    _IMAGE_NAME: medicbook-dev
    _GIT_REPO: https://github.com/xdanadav/medicbook.git
    
steps:
  # Step 1: Pull code from GitHub
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', '${_GIT_REPO}', '.']

  # Step 3: Build and tag Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA', '.']

  # Step 4: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA']

images:
  # Specify the Docker image to be pushed
  - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA'
